spring:
  datasource:
    url: jdbc:sqlite:./kidspos.db
    driverClassName: org.sqlite.JDBC
    sql-script-encoding: utf-8

  jpa:
    properties:
      hibernate:
        id:
          new_generator_mappings=false: false
        temp:
          use_jdbc_metadata_defaults: false
        dialect: com.enigmabridge.hibernate.dialect.SQLiteDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    mode: HTML
server:
  port: 8080
